### ISSUE TITLE
Pin CI's Python3 version

### ISSUE THREAD

**Issue by eliteGoblin** [eliteGoblin/lyubishchev#26]
# NewFeature

## Context

```
jobs:
  run-format-checker:
    runs-on: ubuntu-latest
    steps:
```

Current CI don't specify Python3's version

## Idea, thoughts

We might want to use Python3's latest feature, e.g using native type `tuple[str, str]` in type hint, rather than import from `typing`

## Solution

*  Spike and pin version

## Definition of done

*  Python3 version can be explicitly configured in CI.
